version: '3.9'
services:
  db:
    container_name: vidit_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput && 
      python manage.py init_admin &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env